import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import StoreProvider from '@/app/StoreProvider'
import React from 'react'
import Player from '@/components/player/Player'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<StoreProvider>
			<html lang='en' className='h-full bg-main-bg'>
				<body className={`${GeistSans.className} h-full`}>
					<div className='min-h-full'>
						<Navbar />
						<Player />
						<main className='-mt-32'>
							<div className='mx-auto max-w-7xl px-4 pb-12 sm:px-6 lg:px-8'>
								{children}
							</div>
						</main>
					</div>
				</body>
			</html>
		</StoreProvider>
	)
}
